//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarayTap.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SarayTapEntities : DbContext
    {
        public SarayTapEntities()
            : base("name=SarayTapEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<Managers> Managers { get; set; }
        public virtual DbSet<Pl_Events> Pl_Events { get; set; }
        public virtual DbSet<Pl_Managers> Pl_Managers { get; set; }
        public virtual DbSet<Pl_Services> Pl_Services { get; set; }
        public virtual DbSet<Reservations> Reservations { get; set; }
        public virtual DbSet<Service_Types> Service_Types { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Statuses> Statuses { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Man_Rols> Man_Rols { get; set; }
        public virtual DbSet<Rols> Rols { get; set; }
        public virtual DbSet<Palaces> Palaces { get; set; }
        public virtual DbSet<Images> Images { get; set; }
        public virtual DbSet<Pl_Halls> Pl_Halls { get; set; }
    }
}
