//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarayTap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pl_Services
    {
        public int Id { get; set; }
        public int Palace_Id { get; set; }
        public int Service_Id { get; set; }
        public int Service_Type { get; set; }
    
        public virtual Service_Types Service_Types { get; set; }
        public virtual Services Services { get; set; }
        public virtual Palaces Palaces { get; set; }
    }
}
