//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SarayTap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservations
    {
        public int Id { get; set; }
        public int Hall_Id { get; set; }
        public int Customer_Id { get; set; }
        public System.DateTime Date_Event { get; set; }
        public System.DateTime Date_Request { get; set; }
        public int Status_Id { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual Pl_Halls Pl_Halls { get; set; }
    }
}
